title: Artsgoz API
description: Documentation for the Artsgoz Go API.
theme: just-the-docs
color_scheme: artsgoz
search_enabled: true
nav_enabled: true

url: https://artsgoz.github.io/documentation

aux_links:
  Backend Repository: https://github.com/artsgoz/artsgoz-backend
