title: Artsgoz API
description: Documentation for the Artsgoz Go API.
theme: just-the-docs

url: https://artsgoz.github.io/documentation

aux_links:
  Backend Repository: https://github.com/artsgoz/artsgoz-backend
